#!/bin/sh

# PROVIDE: litestream
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="litestream"
rcvar="litestream_enable"

: ${litestream_enable:=NO}
: ${litestream_config:=/usr/local/etc/litestream.yml}

pidfile="/var/run/litestream/litestream.pid"
supervisor_pidfile="/var/run/litestream/supervisor.pid"
procname="/usr/local/bin/litestream"

command="/usr/sbin/daemon"
command_args="-r -u www -p ${pidfile} -P ${supervisor_pidfile} -f \
    -o /var/log/litestream.log -m 3 \
    /usr/local/www/wagtail/prod/freebsd/scripts/litestream.sh"

load_rc_config $name


start_precmd="litestream_prestart"

litestream_prestart()
{
    install -d -o www -g www -m 755 /var/run/litestream
    rm -f "${pidfile}" "${supervisor_pidfile}" 2>/dev/null || true
}

run_rc_command "$1"
